### PR TITLE
fix no padding problem on RTL Screens

### PR DESCRIPTION
**Pull request by MoaidAlrazhy**

### CODE REVIEW

**Comment by lukepighetti** [comment]
Hi there, can you please resubmit this with the standard 80 line dartfmt settings?

**Comment by MoaidAlrazhy** [comment]
standard 80 line dartfmt done

**Comment by SaadArdati** [comment]
Was about to make this myself! Haha

**Comment by SaadArdati** [comment]
Seems this is not quite right. It's adding excess padding

**Comment by lukepighetti** [comment]
> Seems this is not quite right. It's adding excess padding

Any chance you can contribute to this since you have a better understanding of the problem than I do?

**Comment by lukepighetti** [comment]
closed by https://github.com/lukepighetti/salomon_bottom_bar/pull/16

**Pull request closed without merging**
