### PR TITLE
Properly fix directionality padding.

### PR DESCRIPTION
**Pull request by SaadArdati**
This will correctly fix directionality padding. The look and feel is preserved exactly how it would be with ltr direction.

The other pull request does not do it properly. It adds excess padding.

### CODE REVIEW

**Comment by lukepighetti** [comment]
Thanks for this! Do we need to swap which side the icon is on for RTL? I'm not sure what is standard or not.

**Comment by SaadArdati** [comment]
It already does that automatically :)
Flutter's Rows/Columns are dynamic. It's why axis alignment is called start and end instead of left and right.

**Comment by lukepighetti** [comment]
I can't push to this PR branch for some reason, any ideas?

**Comment by SaadArdati** [comment]
Not sure :( It might be because its a fork and the fork is on my account. I'll try giving you permission to the repo

**Comment by lukepighetti** [comment]
I swear I've done this on fork repos in the past without any drama... hang on

**Comment by lukepighetti** [comment]
If that looks good to you we can merge

**Comment by SaadArdati** [comment]
Looks great to me! Go ahead!

**Comment by lukepighetti** [comment]
Thank you for adding RTL support to `salomon_bottom_bar`!

**Comment by lukepighetti** [comment]
Now available on pub as `salomon_bottom_bar: ^3.2.0`

**Pull request merged**
