### PR TITLE
Added backgroundColor support && Updated deprecated stuff

### PR DESCRIPTION
**Pull request by TiffApps**
Taking the liberty to take over #38 as it's been a while without any progress, and it's been there since #32.

I followed the commands in `Taskfile.yaml`, where I also updated `flutter format` that got deprecated (and `--dry-run` is no longer a thing with`dart format`).

Feel free to edit this PR if there is something wrong or that you don't want to see changed.
Made with latest Flutter version (3.7.1).

Have a nice day!

### CODE REVIEW

**Comment by BaudouinCS** [comment]
I need that, can it get merged please?

**Comment by lukepighetti** [comment]
This isn't going to land until someone does a minimal diff. A minimal diff is when the PR contains only the code needed to add the feature and nothing else. I will handle all the changelogs/versioning/lockfiles etc

**Comment by BaudouinCS** [comment]
The author has respected the Contribution guidelines you provided in the README.md (no "minimal diff" mentioned anywhere), yet you waited for over a month without any reply to their work when you could have easily taken 5min to modify the PR to include only the changes made to the PR as the author also mentioned? They also followed the Taskfile.yaml guidelines, I really don't see the problem with this PR.

**Comment by lukepighetti** [comment]
I have not made any unreasonable requests. I have provided explanations for how to create a minimal diff. My turnaround time on reviews of the original PR was very reasonable. I missed the notification for this one. If someone wants to make this a minimal diff PR I will merge it and handle everything else. This is not a product and I have no paying customers. If someone makes a PR my job is to help them land it, not do the work for them.

**Comment by lukepighetti** [comment]
Closed by #44

**Pull request closed without merging**
