### PR TITLE
✨ Added feature to enable developers specify a background color.

### PR DESCRIPTION
**Pull request by georonathan47**
Developers can now add the preferred `backgroundColor` of their choice by calling the backgroundColor option...

### CODE REVIEW

**Comment by lukepighetti** [comment]
3 questions

- Can the background be changed by wrapping this in a `Container` / `ColoredBox` / `DecoratedBox`?
- Is this the minimal diff required to land this feature?
- Does `BottomNavigationBar` allow for setting of the background color?

**Comment by georonathan47** [comment]
To answer your questions
1: Yes, that's essentially what I did (Wrapping the entire widget around a `Container`)
2. For this question, I'll need to understand what you mean by minimal diff
3. Yes.

**Comment by lukepighetti** [comment]
> If [backgroundColor](https://api.flutter.dev/flutter/material/material/BottomNavigationBar/backgroundColor.html) is null, The navigation bar's background color defaults to the [Material](https://api.flutter.dev/flutter/material/material/Material-class.html) background color, [ThemeData.canvasColor](https://api.flutter.dev/flutter/material/material/ThemeData/canvasColor.html) (essentially opaque white)

[*BottomNavigationBar – Flutter API Docs*](https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html)

Let's copy this functionality, use a ColoredBox, and make this a minimal diff.

A minimal diff is the the absolute minimum code changes needed to add the feature.

**Comment by georonathan47** [comment]
Sure...
I will close this PR and open a new one with the minimal diff using
ColoredBox

**Comment by lukepighetti** [comment]
Sounds good, thanks!

**Pull request closed without merging**
